language: c

compiler:
   - gcc

os:
   - linux

branches:
   only:
      - master
      - stable
      - rewrite

before_install:
   - sudo apt-get -qq update
   - sudo apt-get install -y libtagc
   - sudo apt-get install -y libgstreamer0.9

install:
   - git clone https://github.com/google/googletest
   - cd googletest
   - cmake .
   - make
   - sudo cp googlemock/gtest/libgtest.a /usr/lib
   - sudo cp googlemock/gtest/libgtest_main.a /usr/lib
   - sudo cp -R googletest/include/gtest /usr/include/
   - cd "${TRAVIS_BUILD_DIR}"
